### ISSUE TITLE
关于占位符

### ISSUE THREAD

**Issue by yitong12580** [YueYongDev/flutter_challenge#2]
跳过 $timeOut s

例如这样的多语言 要如何调用呢。

  String get test {
    return Intl.message(
      '跳过 \$timeOut s',
      name: 'l_id_10676',
      desc: '',
      args: [],
    );
  }

这种格式的外部如何调用 
S.of(context).l_id_10676('$timeOut')

**Comment by YueYongDev** [comment]
占位符的用法
arb文件中：
```
{"welcome": "welcome {name}"}
```
使用：
```
S.of(context).welcome("phoenixsky")
```
代码已更新，详情可见
https://github.com/YueYongDev/flutter_challenge/blob/ab25e28b43a4838193410c129c66e31310ae32b0/lib/localizations/localization_page.dart#L38
